"""empty message

Revision ID: 3761dc5949cd
Revises: f97b982ff6dc
Create Date: 2025-05-15 00:37:06.388506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3761dc5949cd'
down_revision = 'f97b982ff6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_services', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('service_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('total_price')
        batch_op.drop_column('service_total')
        batch_op.drop_column('selected_services')

    # ### end Alembic commands ###
