"""description added to room

Revision ID: a9c151f5ddaa
Revises: cb61bbabf0ca
Create Date: 2025-04-25 18:23:15.373034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c151f5ddaa'
down_revision = 'cb61bbabf0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
